#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /opt/Ever Browser/ever-browser 80
    chown root /opt/Ever Browser/chrome-sandbox
    chmod 4755 /opt/Ever Browser/chrome-sandbox
    echo "Run sudo xdg-settings set default-web-browser ever-browser.desktop && sudo update-alternatives --config x-www-browser to set Ever Browser as your default browser."
    ln -sf /opt/Ever Browser/ever-browser /usr/bin/ever-browser
fi
